title: <p align="center"> Gavin Ng </p>

logo: <h2>Rounded Images</h2> <img src="https://avatars.githubusercontent.com/u/70006499?s=400&u=541b359b36a073fd536c288ca63d1d73613e76d0&v=4?raw=true" alt="Avatar" style="width:200px"> 

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/gavin321/">Linkedin</a> |
  <a href="https://public.tableau.com/profile/gavin.ng321/">Tableau</a> |
  <a href="https://tinyurl.com/yc8l9h7y/">Power BI</a> |
  <a href="https://github.com/nspgav">GitHub</a> |
  <a href="https://www.fairprice.com.sg/wps/portal/corporate/corpHome">NTUC Fairprice Group</a>
  </p>
  
  <p align="justify">
  I Lead the Data Analytics function at Internal Audit Department, NTUC Fairprice Group.
  <br><br>
  </p>
  
theme: jekyll-theme-minimal
google_analytics:  # Google Analytics tracking ID
