title: <p align="left"> Gavin Ng </p>

logo: "https://public.tableau.com/avatar/d3da0025-f5f1-4a96-b736-c6d7995f6c15.jpeg?raw=true"

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/gavin321/">Linkedin</a> |
  <a href="https://public.tableau.com/profile/gavin.ng321/">Tableau</a> |
  <a href="https://tinyurl.com/yc8l9h7y/">Power BI</a> 
  </p>
  
  <p align="justify">
  I Lead the Data Analytics function in Internal Audit Department at <a href="https://www.linkedin.com/company/fairprice-group/">NTUC Fairprice Group</a>
  <br><br>
  </p>
  
theme: jekyll-theme-minimal
google_analytics:  # Google Analytics tracking ID
